package io.github.manasmods.tensura.registry.magic;

import dev.architectury.registry.registries.RegistrySupplier;
import io.github.manasmods.manascore.skill.api.ManasSkill;
import io.github.manasmods.manascore.skill.impl.SkillRegistry;
import io.github.manasmods.tensura.ability.magic.aspectual.barrier.AntiMagicAreaMagic;
import io.github.manasmods.tensura.ability.magic.aspectual.barrier.AntiShockAreaMagic;
import io.github.manasmods.tensura.ability.magic.aspectual.barrier.BarrierMagic;
import io.github.manasmods.tensura.ability.magic.aspectual.barrier.MagicBarrierMagic;
import io.github.manasmods.tensura.ability.magic.aspectual.barrier.MagicWallMagic;
import io.github.manasmods.tensura.ability.magic.aspectual.barrier.ReinforcedBarrierMagic;
import io.github.manasmods.tensura.ability.magic.aspectual.earth.EarthLockMagic;
import io.github.manasmods.tensura.ability.magic.aspectual.earth.EarthWallMagic;
import io.github.manasmods.tensura.ability.magic.aspectual.earth.LiquidizeMagic;
import io.github.manasmods.tensura.ability.magic.aspectual.earth.MudHandMagic;
import io.github.manasmods.tensura.ability.magic.aspectual.earth.MudSpearsMagic;
import io.github.manasmods.tensura.ability.magic.aspectual.earth.StoneShotMagic;
import io.github.manasmods.tensura.ability.magic.aspectual.enhancement.AgilityMagic;
import io.github.manasmods.tensura.ability.magic.aspectual.enhancement.ProtectionMagic;
import io.github.manasmods.tensura.ability.magic.aspectual.enhancement.ReinforcementMagic;
import io.github.manasmods.tensura.ability.magic.aspectual.enhancement.StrengthMagic;
import io.github.manasmods.tensura.ability.magic.aspectual.explosion.ChainExplosionMagic;
import io.github.manasmods.tensura.ability.magic.aspectual.explosion.ExplosionMagic;
import io.github.manasmods.tensura.ability.magic.aspectual.fire.FireBallMagic;
import io.github.manasmods.tensura.ability.magic.aspectual.fire.FireLanceMagic;
import io.github.manasmods.tensura.ability.magic.aspectual.fire.FireMagic;
import io.github.manasmods.tensura.ability.magic.aspectual.fire.FireStormMagic;
import io.github.manasmods.tensura.ability.magic.aspectual.fire.FireWallMagic;
import io.github.manasmods.tensura.ability.magic.aspectual.gravity.BurdenMagic;
import io.github.manasmods.tensura.ability.magic.aspectual.gravity.FloatMagic;
import io.github.manasmods.tensura.ability.magic.aspectual.gravity.LightenMagic;
import io.github.manasmods.tensura.ability.magic.aspectual.ice.FreezeMagic;
import io.github.manasmods.tensura.ability.magic.aspectual.ice.IceBlizzardMagic;
import io.github.manasmods.tensura.ability.magic.aspectual.ice.IceBreakerMagic;
import io.github.manasmods.tensura.ability.magic.aspectual.ice.IceWallMagic;
import io.github.manasmods.tensura.ability.magic.aspectual.ice.IcicleLanceMagic;
import io.github.manasmods.tensura.ability.magic.aspectual.ice.IcicleRainMagic;
import io.github.manasmods.tensura.ability.magic.aspectual.ice.IcicleSpearMagic;
import io.github.manasmods.tensura.ability.magic.aspectual.illusion.ConfusionMagic;
import io.github.manasmods.tensura.ability.magic.aspectual.illusion.FlameWallMagic;
import io.github.manasmods.tensura.ability.magic.aspectual.illusion.InvisibleMagic;
import io.github.manasmods.tensura.ability.magic.aspectual.illusion.MirageMagic;
import io.github.manasmods.tensura.ability.magic.aspectual.illusion.PossessionMagic;
import io.github.manasmods.tensura.ability.magic.aspectual.lightning.ThunderLanceMagic;
import io.github.manasmods.tensura.ability.magic.aspectual.lightning.ThunderMagic;
import io.github.manasmods.tensura.ability.magic.aspectual.lightning.ThunderOrbMagic;
import io.github.manasmods.tensura.ability.magic.aspectual.lightning.ThunderRainMagic;
import io.github.manasmods.tensura.ability.magic.aspectual.mental.DemonDominateMagic;
import io.github.manasmods.tensura.ability.magic.aspectual.mental.DemonMarionetteMagic;
import io.github.manasmods.tensura.ability.magic.aspectual.mental.DominateMagic;
import io.github.manasmods.tensura.ability.magic.aspectual.mental.HypnosMagic;
import io.github.manasmods.tensura.ability.magic.aspectual.mental.MentalCrushMagic;
import io.github.manasmods.tensura.ability.magic.aspectual.misc.AnalyzeMagic;
import io.github.manasmods.tensura.ability.magic.aspectual.misc.ClairvoyanceMagic;
import io.github.manasmods.tensura.ability.magic.aspectual.misc.DoppelgangerMagic;
import io.github.manasmods.tensura.ability.magic.aspectual.misc.FlightMagic;
import io.github.manasmods.tensura.ability.magic.aspectual.misc.HealthcareMagic;
import io.github.manasmods.tensura.ability.magic.aspectual.misc.ReincarnationMagic;
import io.github.manasmods.tensura.ability.magic.aspectual.misc.SearchEnemyMagic;
import io.github.manasmods.tensura.ability.magic.aspectual.recovery.AntidoteMagic;
import io.github.manasmods.tensura.ability.magic.aspectual.recovery.FullRecoveryMagic;
import io.github.manasmods.tensura.ability.magic.aspectual.recovery.HealingMagic;
import io.github.manasmods.tensura.ability.magic.aspectual.recovery.HealingRainMagic;
import io.github.manasmods.tensura.ability.magic.aspectual.recovery.RecoveryMagic;
import io.github.manasmods.tensura.ability.magic.aspectual.space.DimensionCutterMagic;
import io.github.manasmods.tensura.ability.magic.aspectual.space.EscapeMagic;
import io.github.manasmods.tensura.ability.magic.aspectual.space.SpatialStorageMagic;
import io.github.manasmods.tensura.ability.magic.aspectual.space.WarpPortalMagic;
import io.github.manasmods.tensura.ability.magic.aspectual.water.AcidShellMagic;
import io.github.manasmods.tensura.ability.magic.aspectual.water.DrainageMagic;
import io.github.manasmods.tensura.ability.magic.aspectual.water.SleepMistMagic;
import io.github.manasmods.tensura.ability.magic.aspectual.water.WaterCutterMagic;
import io.github.manasmods.tensura.ability.magic.aspectual.water.WaterJailMagic;
import io.github.manasmods.tensura.ability.magic.aspectual.water.WaterMagic;
import io.github.manasmods.tensura.ability.magic.aspectual.wind.AirflowShutMagic;
import io.github.manasmods.tensura.ability.magic.aspectual.wind.TornadoBladeMagic;
import io.github.manasmods.tensura.ability.magic.aspectual.wind.WindCutterMagic;
import io.github.manasmods.tensura.ability.magic.aspectual.wind.WindGustMagic;
import io.github.manasmods.tensura.ability.magic.aspectual.wind.WindProtectionMagic;
import java.util.function.Supplier;
import net.minecraft.resources.ResourceLocation;

public class AspectualMagics {
   public static final RegistrySupplier<MagicWallMagic> MAGIC_WALL = register("magic_wall", MagicWallMagic::new);
   public static final RegistrySupplier<MagicBarrierMagic> MAGIC_BARRIER = register("magic_barrier", MagicBarrierMagic::new);
   public static final RegistrySupplier<BarrierMagic> BARRIER = register("barrier", BarrierMagic::new);
   public static final RegistrySupplier<ReinforcedBarrierMagic> REINFORCED_BARRIER = register("reinforced_barrier", ReinforcedBarrierMagic::new);
   public static final RegistrySupplier<AntiShockAreaMagic> ANTI_SHOCK_AREA = register("anti_shock_area", AntiShockAreaMagic::new);
   public static final RegistrySupplier<AntiMagicAreaMagic> ANTI_MAGIC_AREA = register("anti_magic_area", AntiMagicAreaMagic::new);
   public static final RegistrySupplier<EarthLockMagic> EARTH_LOCK = register("earth_lock", EarthLockMagic::new);
   public static final RegistrySupplier<LiquidizeMagic> LIQUIDIZE = register("liquidize", LiquidizeMagic::new);
   public static final RegistrySupplier<EarthWallMagic> EARTH_WALL = register("earth_wall", EarthWallMagic::new);
   public static final RegistrySupplier<MudHandMagic> MUD_HAND = register("mud_hand", MudHandMagic::new);
   public static final RegistrySupplier<StoneShotMagic> STONE_SHOT = register("stone_shot", StoneShotMagic::new);
   public static final RegistrySupplier<MudSpearsMagic> MUD_SPEARS = register("mud_spears", MudSpearsMagic::new);
   public static final RegistrySupplier<ReinforcementMagic> REINFORCEMENT = register("reinforcement", ReinforcementMagic::new);
   public static final RegistrySupplier<StrengthMagic> STRENGTH = register("strength_aspectual", StrengthMagic::new);
   public static final RegistrySupplier<AgilityMagic> AGILITY = register("agility", AgilityMagic::new);
   public static final RegistrySupplier<ProtectionMagic> PROTECTION = register("protection", ProtectionMagic::new);
   public static final RegistrySupplier<ExplosionMagic> EXPLOSION = register("explosion", ExplosionMagic::new);
   public static final RegistrySupplier<ChainExplosionMagic> CHAIN_EXPLOSION = register("chain_explosion", ChainExplosionMagic::new);
   public static final RegistrySupplier<FireMagic> FIRE = register("fire_aspectual", FireMagic::new);
   public static final RegistrySupplier<FireLanceMagic> FIRE_LANCE = register("fire_lance", FireLanceMagic::new);
   public static final RegistrySupplier<FireBallMagic> FIRE_BALL = register("fire_ball", FireBallMagic::new);
   public static final RegistrySupplier<FireWallMagic> FIRE_WALL = register("fire_wall", FireWallMagic::new);
   public static final RegistrySupplier<FireStormMagic> FIRE_STORM = register("fire_storm", FireStormMagic::new);
   public static final RegistrySupplier<FloatMagic> FLOAT = register("float", FloatMagic::new);
   public static final RegistrySupplier<LightenMagic> LIGHTEN = register("lighten", LightenMagic::new);
   public static final RegistrySupplier<BurdenMagic> BURDEN = register("burden", BurdenMagic::new);
   public static final RegistrySupplier<FreezeMagic> FREEZE = register("freeze", FreezeMagic::new);
   public static final RegistrySupplier<IcicleLanceMagic> ICICLE_LANCE = register("icicle_lance", IcicleLanceMagic::new);
   public static final RegistrySupplier<IcicleSpearMagic> ICICLE_SPEAR = register("icicle_spear", IcicleSpearMagic::new);
   public static final RegistrySupplier<IcicleRainMagic> ICICLE_RAIN = register("icicle_rain", IcicleRainMagic::new);
   public static final RegistrySupplier<IceWallMagic> ICE_WALL = register("ice_wall", IceWallMagic::new);
   public static final RegistrySupplier<IceBlizzardMagic> ICE_BLIZZARD = register("ice_blizzard", IceBlizzardMagic::new);
   public static final RegistrySupplier<IceBreakerMagic> ICE_BREAKER = register("ice_breaker", IceBreakerMagic::new);
   public static final RegistrySupplier<FlameWallMagic> FLAME_WALL = register("flame_wall", FlameWallMagic::new);
   public static final RegistrySupplier<ConfusionMagic> CONFUSION = register("confusion", ConfusionMagic::new);
   public static final RegistrySupplier<InvisibleMagic> INVISIBLE = register("invisible", InvisibleMagic::new);
   public static final RegistrySupplier<MirageMagic> MIRAGE = register("mirage", MirageMagic::new);
   public static final RegistrySupplier<PossessionMagic> POSSESSION = register("possession_magic", PossessionMagic::new);
   public static final RegistrySupplier<ThunderLanceMagic> THUNDER_LANCE = register("thunder_lance", ThunderLanceMagic::new);
   public static final RegistrySupplier<ThunderMagic> THUNDER = register("thunder", ThunderMagic::new);
   public static final RegistrySupplier<ThunderOrbMagic> THUNDER_ORB = register("thunder_orb", ThunderOrbMagic::new);
   public static final RegistrySupplier<ThunderRainMagic> THUNDER_RAIN = register("thunder_rain", ThunderRainMagic::new);
   public static final RegistrySupplier<DominateMagic> DOMINATE = register("dominate", DominateMagic::new);
   public static final RegistrySupplier<DemonDominateMagic> DEMON_DOMINATE = register("demon_dominate", DemonDominateMagic::new);
   public static final RegistrySupplier<DemonMarionetteMagic> DEMON_MARIONETTE = register("demon_marionette", DemonMarionetteMagic::new);
   public static final RegistrySupplier<MentalCrushMagic> MENTAL_CRUSH = register("mental_crush", MentalCrushMagic::new);
   public static final RegistrySupplier<HypnosMagic> HYPNOS = register("hypnos", HypnosMagic::new);
   public static final RegistrySupplier<HealingMagic> HEALING = register("healing", HealingMagic::new);
   public static final RegistrySupplier<HealingRainMagic> HEALING_RAIN = register("healing_rain", HealingRainMagic::new);
   public static final RegistrySupplier<RecoveryMagic> RECOVERY = register("recovery", RecoveryMagic::new);
   public static final RegistrySupplier<AntidoteMagic> ANTIDOTE = register("antidote", AntidoteMagic::new);
   public static final RegistrySupplier<FullRecoveryMagic> FULL_RECOVERY = register("full_recovery", FullRecoveryMagic::new);
   public static final RegistrySupplier<EscapeMagic> ESCAPE = register("escape", EscapeMagic::new);
   public static final RegistrySupplier<WarpPortalMagic> WARP_PORTAL = register("warp_portal", WarpPortalMagic::new);
   public static final RegistrySupplier<SpatialStorageMagic> SPATIAL_STORAGE = register("spatial_storage", SpatialStorageMagic::new);
   public static final RegistrySupplier<DimensionCutterMagic> DIMENSION_CUTTER = register("dimension_cutter", DimensionCutterMagic::new);
   public static final RegistrySupplier<WaterMagic> WATER = register("water_aspectual", WaterMagic::new);
   public static final RegistrySupplier<DrainageMagic> DRAINAGE = register("drainage", DrainageMagic::new);
   public static final RegistrySupplier<WaterCutterMagic> WATER_CUTTER = register("water_cutter_aspectual", WaterCutterMagic::new);
   public static final RegistrySupplier<WaterJailMagic> WATER_JAIL = register("water_jail", WaterJailMagic::new);
   public static final RegistrySupplier<SleepMistMagic> SLEEP_MIST = register("sleep_mist", SleepMistMagic::new);
   public static final RegistrySupplier<AcidShellMagic> ACID_SHELL = register("acid_shell", AcidShellMagic::new);
   public static final RegistrySupplier<WindGustMagic> WIND_GUST = register("wind_gust", WindGustMagic::new);
   public static final RegistrySupplier<WindCutterMagic> WIND_CUTTER = register("wind_cutter", WindCutterMagic::new);
   public static final RegistrySupplier<TornadoBladeMagic> TORNADO_BLADE = register("tornado_blade", TornadoBladeMagic::new);
   public static final RegistrySupplier<WindProtectionMagic> WIND_PROTECTION = register("wind_protection", WindProtectionMagic::new);
   public static final RegistrySupplier<AirflowShutMagic> AIRFLOW_SHUT = register("airflow_shut", AirflowShutMagic::new);
   public static final RegistrySupplier<ReincarnationMagic> REINCARNATION = register("reincarnation", ReincarnationMagic::new);
   public static final RegistrySupplier<AnalyzeMagic> ANALYZE = register("analyze", AnalyzeMagic::new);
   public static final RegistrySupplier<ClairvoyanceMagic> CLAIRVOYANCE = register("clairvoyance", ClairvoyanceMagic::new);
   public static final RegistrySupplier<DoppelgangerMagic> DOPPELGANGER = register("doppelganger", DoppelgangerMagic::new);
   public static final RegistrySupplier<FlightMagic> FLIGHT = register("flight", FlightMagic::new);
   public static final RegistrySupplier<HealthcareMagic> HEALTHCARE = register("healthcare", HealthcareMagic::new);
   public static final RegistrySupplier<SearchEnemyMagic> SEARCH_ENEMY = register("search_enemy", SearchEnemyMagic::new);

   private static <E extends ManasSkill> RegistrySupplier<E> register(String name, Supplier<E> supplier) {
      return SkillRegistry.SKILLS.register(ResourceLocation.fromNamespaceAndPath("tensura", name), supplier);
   }

   public static void init() {
   }
}
