package io.github.manasmods.tensura.registry.sound;

import dev.architectury.registry.registries.DeferredRegister;
import dev.architectury.registry.registries.RegistrySupplier;
import net.minecraft.core.registries.Registries;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.sounds.SoundEvent;

public class TensuraSoundEvents {
   private static final DeferredRegister<SoundEvent> SOUND_EVENTS = DeferredRegister.create("tensura", Registries.SOUND_EVENT);
   public static final RegistrySupplier<SoundEvent> NANODA = register("music_disc.nanoda");
   public static final RegistrySupplier<SoundEvent> BUFF_ACTIVATE = register("ability.buff.activate");
   public static final RegistrySupplier<SoundEvent> BUFF_DEACTIVATE = register("ability.buff.deactivate");
   public static final RegistrySupplier<SoundEvent> DEBUFF_ACTIVATE = register("ability.debuff.activate");
   public static final RegistrySupplier<SoundEvent> DEBUFF_DEACTIVATE = register("ability.debuff.deactivate");
   public static final RegistrySupplier<SoundEvent> DEFENCE_ACTIVATE = register("ability.defence.activate");
   public static final RegistrySupplier<SoundEvent> DEFENCE_DEACTIVATE = register("ability.defence.deactivate");
   public static final RegistrySupplier<SoundEvent> GENERIC_CAST = register("ability.cast.generic");
   public static final RegistrySupplier<SoundEvent> GENERIC_CAST_FAIL = register("ability.cast.generic_fail");
   public static final RegistrySupplier<SoundEvent> GENERIC_UNCAST = register("ability.cast.generic_uncast");
   public static final RegistrySupplier<SoundEvent> GENERIC_HEAL = register("ability.cast.generic_heal");
   public static final RegistrySupplier<SoundEvent> GENERIC_SPLIT = register("ability.cast.generic_split");
   public static final RegistrySupplier<SoundEvent> ENERGY_DRAIN = register("ability.cast.energy_drain");
   public static final RegistrySupplier<SoundEvent> PRESENCE_CONCEALMENT = register("ability.cast.presence_concealment");
   public static final RegistrySupplier<SoundEvent> CAST_DARK = register("ability.cast.dark_cast");
   public static final RegistrySupplier<SoundEvent> CAST_EARTH = register("ability.cast.earth_cast");
   public static final RegistrySupplier<SoundEvent> CAST_FIRE = register("ability.cast.fire_cast");
   public static final RegistrySupplier<SoundEvent> CAST_LIGHT = register("ability.cast.light_cast");
   public static final RegistrySupplier<SoundEvent> CAST_LIGHTNING = register("ability.cast.lightning_cast");
   public static final RegistrySupplier<SoundEvent> CAST_ICE = register("ability.cast.ice_cast");
   public static final RegistrySupplier<SoundEvent> CAST_SPACE = register("ability.cast.space_cast");
   public static final RegistrySupplier<SoundEvent> CAST_WATER = register("ability.cast.water_cast");
   public static final RegistrySupplier<SoundEvent> CAST_WIND = register("ability.cast.wind_cast");
   public static final RegistrySupplier<SoundEvent> BLOOD_RAY = register("ability.blood_ray.loop");
   public static final RegistrySupplier<SoundEvent> BREATH_FIRE = register("ability.breath.fire");
   public static final RegistrySupplier<SoundEvent> BREATH_POISON = register("ability.breath.poison");
   public static final RegistrySupplier<SoundEvent> BREATH_THUNDER = register("ability.breath.thunder");
   public static final RegistrySupplier<SoundEvent> BREATH_WATER = register("ability.breath.water");
   public static final RegistrySupplier<SoundEvent> BREATH_WIND = register("ability.breath.wind");
   public static final RegistrySupplier<SoundEvent> COERCION = register("ability.coercion.start");
   public static final RegistrySupplier<SoundEvent> MIST_RELEASE = register("ability.mist.release");
   public static final RegistrySupplier<SoundEvent> TRANSFORM_BEAST = register("ability.transform.beast");
   public static final RegistrySupplier<SoundEvent> TRANSFORM_DRAGON = register("ability.transform.dragon");
   public static final RegistrySupplier<SoundEvent> TRANSFORM_OGRE = register("ability.transform.ogre");
   public static final RegistrySupplier<SoundEvent> TRANSFORM_BERSERKER = register("ability.transform.berserker");
   public static final RegistrySupplier<SoundEvent> HAKI_START = register("ability.haki.start");
   public static final RegistrySupplier<SoundEvent> HAKI_LOOP = register("ability.haki.loop");
   public static final RegistrySupplier<SoundEvent> BARRIER_BREAK = register("ability.barrier.break");
   public static final RegistrySupplier<SoundEvent> STICKY_STEEL_THREAD = register("ability.sticky_steel_thread.start");
   public static final RegistrySupplier<SoundEvent> EATER = register("ability.eater.start");
   public static final RegistrySupplier<SoundEvent> MUSIC_BLAST = register("ability.music.blast");
   public static final RegistrySupplier<SoundEvent> MUSIC_REQUIEM = register("ability.music.requiem");
   public static final RegistrySupplier<SoundEvent> SPATIAL_STORAGE = register("ability.storage.open");
   public static final RegistrySupplier<SoundEvent> PREDATION = register("ability.predation.loop");
   public static final RegistrySupplier<SoundEvent> REFLECTION = register("ability.reflection.reverse");
   public static final RegistrySupplier<SoundEvent> EARTHSHATTER_KICK = register("ability.earthshatter_kick.start");
   public static final RegistrySupplier<SoundEvent> INSTANT_MOVE = register("ability.instant_move.start");
   public static final RegistrySupplier<SoundEvent> DISINTEGRATION = register("ability.disintegration.start");
   public static final RegistrySupplier<SoundEvent> MEGIDDO_SHOOT = register("ability.megiddo.shoot");
   public static final RegistrySupplier<SoundEvent> SWIPE = register("ability.swipe.start");
   public static final RegistrySupplier<SoundEvent> ACID_SIZZLE = register("effect.acid.sizzle");
   public static final RegistrySupplier<SoundEvent> WIND_BLOW = register("entity.wind.blow");
   public static final RegistrySupplier<SoundEvent> BIG_BITE = register("entity.bite.big");
   public static final RegistrySupplier<SoundEvent> GENERIC_SPLASH = register("entity.generic.splash");
   public static final RegistrySupplier<SoundEvent> GENERIC_WATER_JUMP = register("entity.generic.water_jump");
   public static final RegistrySupplier<SoundEvent> ARMORSAURUS_AMBIENT = register("entity.armorsaurus.ambient");
   public static final RegistrySupplier<SoundEvent> ARMORSAURUS_HURT = register("entity.armorsaurus.hurt");
   public static final RegistrySupplier<SoundEvent> ARMORSAURUS_DEATH = register("entity.armorsaurus.death");
   public static final RegistrySupplier<SoundEvent> BARGHEST_AMBIENT = register("entity.barghest.ambient");
   public static final RegistrySupplier<SoundEvent> BARGHEST_AGGRO = register("entity.barghest.aggro");
   public static final RegistrySupplier<SoundEvent> BARGHEST_HURT = register("entity.barghest.hurt");
   public static final RegistrySupplier<SoundEvent> BARGHEST_DEATH = register("entity.barghest.death");
   public static final RegistrySupplier<SoundEvent> BASILISK_AMBIENT = register("entity.basilisk.ambient");
   public static final RegistrySupplier<SoundEvent> BASILISK_HURT = register("entity.basilisk.hurt");
   public static final RegistrySupplier<SoundEvent> BASILISK_DEATH = register("entity.basilisk.death");
   public static final RegistrySupplier<SoundEvent> BEAR_AMBIENT = register("entity.bear.ambient");
   public static final RegistrySupplier<SoundEvent> BEAR_ATTACK = register("entity.bear.aggro");
   public static final RegistrySupplier<SoundEvent> BEAR_HURT = register("entity.bear.hurt");
   public static final RegistrySupplier<SoundEvent> BEAR_DEATH = register("entity.bear.death");
   public static final RegistrySupplier<SoundEvent> BIRD_AMBIENT = register("entity.bird.ambient");
   public static final RegistrySupplier<SoundEvent> BIRD_HURT = register("entity.bird.hurt");
   public static final RegistrySupplier<SoundEvent> BIRD_DEATH = register("entity.bird.death");
   public static final RegistrySupplier<SoundEvent> CAT_AMBIENT = register("entity.cat.ambient");
   public static final RegistrySupplier<SoundEvent> CAT_AGGRO = register("entity.cat.aggro");
   public static final RegistrySupplier<SoundEvent> CAT_HURT = register("entity.cat.hurt");
   public static final RegistrySupplier<SoundEvent> CAT_DEATH = register("entity.cat.death");
   public static final RegistrySupplier<SoundEvent> CENTIPEDE_AMBIENT = register("entity.centipede.ambient");
   public static final RegistrySupplier<SoundEvent> CENTIPEDE_HURT = register("entity.centipede.hurt");
   public static final RegistrySupplier<SoundEvent> CENTIPEDE_DEATH = register("entity.centipede.death");
   public static final RegistrySupplier<SoundEvent> DAEMON_AMBIENT = register("entity.daemon.ambient");
   public static final RegistrySupplier<SoundEvent> DAEMON_HURT = register("entity.daemon.hurt");
   public static final RegistrySupplier<SoundEvent> DAEMON_DEATH = register("entity.daemon.death");
   public static final RegistrySupplier<SoundEvent> DIREWOLF_AMBIENT = register("entity.direwolf.ambient");
   public static final RegistrySupplier<SoundEvent> DIREWOLF_AGGRO = register("entity.direwolf.aggro");
   public static final RegistrySupplier<SoundEvent> DIREWOLF_HOWL = register("entity.direwolf.howl");
   public static final RegistrySupplier<SoundEvent> DIREWOLF_HURT = register("entity.direwolf.hurt");
   public static final RegistrySupplier<SoundEvent> DIREWOLF_DEATH = register("entity.direwolf.death");
   public static final RegistrySupplier<SoundEvent> DOG_AMBIENT = register("entity.dog.ambient");
   public static final RegistrySupplier<SoundEvent> DOG_AGGRO = register("entity.dog.aggro");
   public static final RegistrySupplier<SoundEvent> DOG_HURT = register("entity.dog.hurt");
   public static final RegistrySupplier<SoundEvent> DOG_DEATH = register("entity.dog.death");
   public static final RegistrySupplier<SoundEvent> FISH_FLOP = register("entity.fish.flop");
   public static final RegistrySupplier<SoundEvent> FISH_HURT = register("entity.fish.hurt");
   public static final RegistrySupplier<SoundEvent> FISH_DEATH = register("entity.fish.death");
   public static final RegistrySupplier<SoundEvent> GNOME_AMBIENT = register("entity.gnome.ambient");
   public static final RegistrySupplier<SoundEvent> GNOME_HURT = register("entity.gnome.hurt");
   public static final RegistrySupplier<SoundEvent> GNOME_DEATH = register("entity.gnome.death");
   public static final RegistrySupplier<SoundEvent> GOBLIN_AMBIENT = register("entity.goblin.ambient");
   public static final RegistrySupplier<SoundEvent> GOBLIN_AGGRO = register("entity.goblin.aggro");
   public static final RegistrySupplier<SoundEvent> GOBLIN_HURT = register("entity.goblin.hurt");
   public static final RegistrySupplier<SoundEvent> GOBLIN_DEATH = register("entity.goblin.death");
   public static final RegistrySupplier<SoundEvent> GOLEM_AMBIENT = register("entity.golem.ambient");
   public static final RegistrySupplier<SoundEvent> GOLEM_HURT = register("entity.golem.hurt");
   public static final RegistrySupplier<SoundEvent> GOLEM_DEATH = register("entity.golem.death");
   public static final RegistrySupplier<SoundEvent> HOVER_LIZARD_AMBIENT = register("entity.hover_lizard.ambient");
   public static final RegistrySupplier<SoundEvent> HOVER_LIZARD_HURT = register("entity.hover_lizard.hurt");
   public static final RegistrySupplier<SoundEvent> HOVER_LIZARD_DEATH = register("entity.hover_lizard.death");
   public static final RegistrySupplier<SoundEvent> INSECT_AMBIENT = register("entity.insect.ambient");
   public static final RegistrySupplier<SoundEvent> INSECT_FLY = register("entity.insect.fly");
   public static final RegistrySupplier<SoundEvent> INSECT_HURT = register("entity.insect.hurt");
   public static final RegistrySupplier<SoundEvent> INSECT_DEATH = register("entity.insect.death");
   public static final RegistrySupplier<SoundEvent> LEECH_LIZARD_AMBIENT = register("entity.leech_lizard.ambient");
   public static final RegistrySupplier<SoundEvent> LEECH_LIZARD_ATTACK = register("entity.leech_lizard.attack");
   public static final RegistrySupplier<SoundEvent> LEECH_LIZARD_HURT = register("entity.leech_lizard.hurt");
   public static final RegistrySupplier<SoundEvent> LEECH_LIZARD_DEATH = register("entity.leech_lizard.death");
   public static final RegistrySupplier<SoundEvent> LIZARDMAN_AMBIENT = register("entity.lizardman.ambient");
   public static final RegistrySupplier<SoundEvent> LIZARDMAN_HURT = register("entity.lizardman.hurt");
   public static final RegistrySupplier<SoundEvent> LIZARDMAN_DEATH = register("entity.lizardman.death");
   public static final RegistrySupplier<SoundEvent> MEGALODON_AMBIENT = register("entity.megalodon.ambient");
   public static final RegistrySupplier<SoundEvent> MEGALODON_HURT = register("entity.megalodon.hurt");
   public static final RegistrySupplier<SoundEvent> MEGALODON_DEATH = register("entity.megalodon.death");
   public static final RegistrySupplier<SoundEvent> OWL_AMBIENT = register("entity.owl.ambient");
   public static final RegistrySupplier<SoundEvent> OWL_HURT = register("entity.owl.hurt");
   public static final RegistrySupplier<SoundEvent> OWL_DEATH = register("entity.owl.death");
   public static final RegistrySupplier<SoundEvent> SISSIE_AMBIENT = register("entity.sissie.ambient");
   public static final RegistrySupplier<SoundEvent> SISSIE_HURT = register("entity.sissie.hurt");
   public static final RegistrySupplier<SoundEvent> SISSIE_DEATH = register("entity.sissie.death");
   public static final RegistrySupplier<SoundEvent> SPEAR_TORO_AMBIENT = register("entity.spear_toro.ambient");
   public static final RegistrySupplier<SoundEvent> SPEAR_TORO_HURT = register("entity.spear_toro.hurt");
   public static final RegistrySupplier<SoundEvent> SPEAR_TORO_DEATH = register("entity.spear_toro.death");
   public static final RegistrySupplier<SoundEvent> SERPENT_AMBIENT = register("entity.serpent.ambient");
   public static final RegistrySupplier<SoundEvent> SERPENT_HURT = register("entity.serpent.hurt");
   public static final RegistrySupplier<SoundEvent> SERPENT_DEATH = register("entity.serpent.death");
   public static final RegistrySupplier<SoundEvent> SPIRIT_FLAME_AMBIENT = register("entity.spirit_flame.ambient");
   public static final RegistrySupplier<SoundEvent> SPIRIT_FLAME_HURT = register("entity.spirit_flame.hurt");
   public static final RegistrySupplier<SoundEvent> SPIRIT_FLAME_DEATH = register("entity.spirit_flame.death");
   public static final RegistrySupplier<SoundEvent> SPIRIT_SPACE_AMBIENT = register("entity.spirit_space.ambient");
   public static final RegistrySupplier<SoundEvent> SPIRIT_SPACE_HURT = register("entity.spirit_space.hurt");
   public static final RegistrySupplier<SoundEvent> SPIRIT_SPACE_DEATH = register("entity.spirit_space.death");
   public static final RegistrySupplier<SoundEvent> SPIRIT_WATER_AMBIENT = register("entity.spirit_water.ambient");
   public static final RegistrySupplier<SoundEvent> SPIRIT_WATER_HURT = register("entity.spirit_water.hurt");
   public static final RegistrySupplier<SoundEvent> SPIRIT_WATER_DEATH = register("entity.spirit_water.death");
   public static final RegistrySupplier<SoundEvent> SPIRIT_WIND_AMBIENT = register("entity.spirit_wind.ambient");
   public static final RegistrySupplier<SoundEvent> SPIRIT_WIND_HURT = register("entity.spirit_wind.hurt");
   public static final RegistrySupplier<SoundEvent> SPIRIT_WIND_DEATH = register("entity.spirit_wind.death");
   public static final RegistrySupplier<SoundEvent> METAL_SLIME_SQUISH = register("entity.metal_slime.squish");
   public static final RegistrySupplier<SoundEvent> METAL_SLIME_ATTACK = register("entity.metal_slime.attack");
   public static final RegistrySupplier<SoundEvent> METAL_SLIME_HURT = register("entity.metal_slime.hurt");
   public static final RegistrySupplier<SoundEvent> METAL_SLIME_DEATH = register("entity.metal_slime.death");
   public static final RegistrySupplier<SoundEvent> ORC_AMBIENT = register("entity.orc.ambient");
   public static final RegistrySupplier<SoundEvent> ORC_HURT = register("entity.orc.hurt");
   public static final RegistrySupplier<SoundEvent> ORC_DEATH = register("entity.orc.death");
   public static final RegistrySupplier<SoundEvent> ORC_LAUGH = register("entity.orc.laugh");
   public static final RegistrySupplier<SoundEvent> ORC_TRANSFORM = register("entity.orc.transform");
   public static final RegistrySupplier<SoundEvent> TIGER_AMBIENT = register("entity.tiger.ambient");
   public static final RegistrySupplier<SoundEvent> TIGER_ATTACK = register("entity.tiger.aggro");
   public static final RegistrySupplier<SoundEvent> TIGER_HURT = register("entity.tiger.hurt");
   public static final RegistrySupplier<SoundEvent> TIGER_DEATH = register("entity.tiger.death");

   private static RegistrySupplier<SoundEvent> register(String id) {
      return SOUND_EVENTS.register(id, () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath("tensura", id)));
   }

   public static void init() {
      SOUND_EVENTS.register();
   }
}
