package io.github.manasmods.tensura.registry.skill;

import dev.architectury.registry.registries.RegistrySupplier;
import io.github.manasmods.manascore.skill.api.ManasSkill;
import io.github.manasmods.manascore.skill.impl.SkillRegistry;
import io.github.manasmods.tensura.ability.skill.unique.AbsoluteSeveranceSkill;
import io.github.manasmods.tensura.ability.skill.unique.AnalystSkill;
import io.github.manasmods.tensura.ability.skill.unique.AntiSkill;
import io.github.manasmods.tensura.ability.skill.unique.BerserkSkill;
import io.github.manasmods.tensura.ability.skill.unique.BerserkerSkill;
import io.github.manasmods.tensura.ability.skill.unique.BewilderSkill;
import io.github.manasmods.tensura.ability.skill.unique.ChefSkill;
import io.github.manasmods.tensura.ability.skill.unique.ChosenOneSkill;
import io.github.manasmods.tensura.ability.skill.unique.CommanderSkill;
import io.github.manasmods.tensura.ability.skill.unique.CookSkill;
import io.github.manasmods.tensura.ability.skill.unique.CreatorSkill;
import io.github.manasmods.tensura.ability.skill.unique.DegenerateSkill;
import io.github.manasmods.tensura.ability.skill.unique.DivineBerserkerSkill;
import io.github.manasmods.tensura.ability.skill.unique.EngorgerSkill;
import io.github.manasmods.tensura.ability.skill.unique.EnvySkill;
import io.github.manasmods.tensura.ability.skill.unique.FalsifierSkill;
import io.github.manasmods.tensura.ability.skill.unique.FighterSkill;
import io.github.manasmods.tensura.ability.skill.unique.FusionistSkill;
import io.github.manasmods.tensura.ability.skill.unique.GluttonySkill;
import io.github.manasmods.tensura.ability.skill.unique.GodlyCraftsmanSkill;
import io.github.manasmods.tensura.ability.skill.unique.GourmandSkill;
import io.github.manasmods.tensura.ability.skill.unique.GourmetSkill;
import io.github.manasmods.tensura.ability.skill.unique.GreatSageSkill;
import io.github.manasmods.tensura.ability.skill.unique.GreedSkill;
import io.github.manasmods.tensura.ability.skill.unique.GuardianSkill;
import io.github.manasmods.tensura.ability.skill.unique.HealerSkill;
import io.github.manasmods.tensura.ability.skill.unique.InfinityPrisonSkill;
import io.github.manasmods.tensura.ability.skill.unique.LustSkill;
import io.github.manasmods.tensura.ability.skill.unique.MartialMasterSkill;
import io.github.manasmods.tensura.ability.skill.unique.MathematicianSkill;
import io.github.manasmods.tensura.ability.skill.unique.MercilessSkill;
import io.github.manasmods.tensura.ability.skill.unique.MurdererSkill;
import io.github.manasmods.tensura.ability.skill.unique.MusicianSkill;
import io.github.manasmods.tensura.ability.skill.unique.ObserverSkill;
import io.github.manasmods.tensura.ability.skill.unique.OppressorSkill;
import io.github.manasmods.tensura.ability.skill.unique.PredatorSkill;
import io.github.manasmods.tensura.ability.skill.unique.PrideSkill;
import io.github.manasmods.tensura.ability.skill.unique.ReaperSkill;
import io.github.manasmods.tensura.ability.skill.unique.ReflectorSkill;
import io.github.manasmods.tensura.ability.skill.unique.ResearcherSkill;
import io.github.manasmods.tensura.ability.skill.unique.ReverserSkill;
import io.github.manasmods.tensura.ability.skill.unique.RoyalBeastSkill;
import io.github.manasmods.tensura.ability.skill.unique.SeekerSkill;
import io.github.manasmods.tensura.ability.skill.unique.SeerSkill;
import io.github.manasmods.tensura.ability.skill.unique.SevererSkill;
import io.github.manasmods.tensura.ability.skill.unique.ShadowStrikerSkill;
import io.github.manasmods.tensura.ability.skill.unique.SlothSkill;
import io.github.manasmods.tensura.ability.skill.unique.SniperSkill;
import io.github.manasmods.tensura.ability.skill.unique.SpearheadSkill;
import io.github.manasmods.tensura.ability.skill.unique.StarvedSkill;
import io.github.manasmods.tensura.ability.skill.unique.SuppressorSkill;
import io.github.manasmods.tensura.ability.skill.unique.SurvivorSkill;
import io.github.manasmods.tensura.ability.skill.unique.ThrowerSkill;
import io.github.manasmods.tensura.ability.skill.unique.TravelerSkill;
import io.github.manasmods.tensura.ability.skill.unique.TunerSkill;
import io.github.manasmods.tensura.ability.skill.unique.UnyieldingSkill;
import io.github.manasmods.tensura.ability.skill.unique.UsurperSkill;
import io.github.manasmods.tensura.ability.skill.unique.VillainSkill;
import io.github.manasmods.tensura.ability.skill.unique.WrathSkill;
import java.util.function.Supplier;
import net.minecraft.resources.ResourceLocation;

public class UniqueSkills {
   public static final RegistrySupplier<AbsoluteSeveranceSkill> ABSOLUTE_SEVERANCE = register("absolute_severance", AbsoluteSeveranceSkill::new);
   public static final RegistrySupplier<AnalystSkill> ANALYST = register("analyst", AnalystSkill::new);
   public static final RegistrySupplier<AntiSkill> ANTI_SKILL = register("anti_skill", AntiSkill::new);
   public static final RegistrySupplier<BerserkerSkill> BERSERKER = register("berserker", BerserkerSkill::new);
   public static final RegistrySupplier<BerserkSkill> BERSERK = register("berserk", BerserkSkill::new);
   public static final RegistrySupplier<BewilderSkill> BEWILDER = register("bewilder", BewilderSkill::new);
   public static final RegistrySupplier<ChefSkill> CHEF = register("chef", ChefSkill::new);
   public static final RegistrySupplier<ChosenOneSkill> CHOSEN_ONE = register("chosen_one", ChosenOneSkill::new);
   public static final RegistrySupplier<CommanderSkill> COMMANDER = register("commander", CommanderSkill::new);
   public static final RegistrySupplier<CookSkill> COOK = register("cook", CookSkill::new);
   public static final RegistrySupplier<CreatorSkill> CREATOR = register("creator", CreatorSkill::new);
   public static final RegistrySupplier<DegenerateSkill> DEGENERATE = register("degenerate", DegenerateSkill::new);
   public static final RegistrySupplier<DivineBerserkerSkill> DIVINE_BERSERKER = register("divine_berserker", DivineBerserkerSkill::new);
   public static final RegistrySupplier<EngorgerSkill> ENGORGER = register("engorger", EngorgerSkill::new);
   public static final RegistrySupplier<EnvySkill> ENVY = register("envy", EnvySkill::new);
   public static final RegistrySupplier<FalsifierSkill> FALSIFIER = register("falsifier", FalsifierSkill::new);
   public static final RegistrySupplier<FighterSkill> FIGHTER = register("fighter", FighterSkill::new);
   public static final RegistrySupplier<FusionistSkill> FUSIONIST = register("fusionist", FusionistSkill::new);
   public static final RegistrySupplier<GluttonySkill> GLUTTONY = register("gluttony", GluttonySkill::new);
   public static final RegistrySupplier<GodlyCraftsmanSkill> GODLY_CRAFTSMAN = register("godly_craftsman", GodlyCraftsmanSkill::new);
   public static final RegistrySupplier<GourmandSkill> GOURMAND = register("gourmand", GourmandSkill::new);
   public static final RegistrySupplier<GourmetSkill> GOURMET = register("gourmet", GourmetSkill::new);
   public static final RegistrySupplier<GreatSageSkill> GREAT_SAGE = register("great_sage", GreatSageSkill::new);
   public static final RegistrySupplier<GreedSkill> GREED = register("greed", GreedSkill::new);
   public static final RegistrySupplier<GuardianSkill> GUARDIAN = register("guardian", GuardianSkill::new);
   public static final RegistrySupplier<HealerSkill> HEALER = register("healer", HealerSkill::new);
   public static final RegistrySupplier<InfinityPrisonSkill> INFINITY_PRISON = register("infinity_prison", InfinityPrisonSkill::new);
   public static final RegistrySupplier<LustSkill> LUST = register("lust", LustSkill::new);
   public static final RegistrySupplier<MartialMasterSkill> MARTIAL_MASTER = register("martial_master", MartialMasterSkill::new);
   public static final RegistrySupplier<MathematicianSkill> MATHEMATICIAN = register("mathematician", MathematicianSkill::new);
   public static final RegistrySupplier<MercilessSkill> MERCILESS = register("merciless", MercilessSkill::new);
   public static final RegistrySupplier<MurdererSkill> MURDERER = register("murderer", MurdererSkill::new);
   public static final RegistrySupplier<MusicianSkill> MUSICIAN = register("musician", MusicianSkill::new);
   public static final RegistrySupplier<ObserverSkill> OBSERVER = register("observer", ObserverSkill::new);
   public static final RegistrySupplier<OppressorSkill> OPPRESSOR = register("oppressor", OppressorSkill::new);
   public static final RegistrySupplier<PredatorSkill> PREDATOR = register("predator", PredatorSkill::new);
   public static final RegistrySupplier<PrideSkill> PRIDE = register("pride", PrideSkill::new);
   public static final RegistrySupplier<ReflectorSkill> REFLECTOR = register("reflector", ReflectorSkill::new);
   public static final RegistrySupplier<ResearcherSkill> RESEARCHER = register("researcher", ResearcherSkill::new);
   public static final RegistrySupplier<RoyalBeastSkill> ROYAL_BEAST = register("royal_beast", RoyalBeastSkill::new);
   public static final RegistrySupplier<ReaperSkill> REAPER = register("reaper", ReaperSkill::new);
   public static final RegistrySupplier<ReverserSkill> REVERSER = register("reverser", ReverserSkill::new);
   public static final RegistrySupplier<SeekerSkill> SEEKER = register("seeker", SeekerSkill::new);
   public static final RegistrySupplier<SeerSkill> SEER = register("seer", SeerSkill::new);
   public static final RegistrySupplier<SevererSkill> SEVERER = register("severer", SevererSkill::new);
   public static final RegistrySupplier<ShadowStrikerSkill> SHADOW_STRIKER = register("shadow_striker", ShadowStrikerSkill::new);
   public static final RegistrySupplier<SlothSkill> SLOTH = register("sloth", SlothSkill::new);
   public static final RegistrySupplier<SniperSkill> SNIPER = register("sniper", SniperSkill::new);
   public static final RegistrySupplier<SpearheadSkill> SPEARHEAD = register("spearhead", SpearheadSkill::new);
   public static final RegistrySupplier<StarvedSkill> STARVED = register("starved", StarvedSkill::new);
   public static final RegistrySupplier<SuppressorSkill> SUPPRESSOR = register("suppressor", SuppressorSkill::new);
   public static final RegistrySupplier<SurvivorSkill> SURVIVOR = register("survivor", SurvivorSkill::new);
   public static final RegistrySupplier<ThrowerSkill> THROWER = register("thrower", ThrowerSkill::new);
   public static final RegistrySupplier<TravelerSkill> TRAVELER = register("traveler", TravelerSkill::new);
   public static final RegistrySupplier<TunerSkill> TUNER = register("tuner", TunerSkill::new);
   public static final RegistrySupplier<UnyieldingSkill> UNYIELDING = register("unyielding", UnyieldingSkill::new);
   public static final RegistrySupplier<UsurperSkill> USURPER = register("usurper", UsurperSkill::new);
   public static final RegistrySupplier<VillainSkill> VILLAIN = register("villain", VillainSkill::new);
   public static final RegistrySupplier<WrathSkill> WRATH = register("wrath", WrathSkill::new);

   private static <E extends ManasSkill> RegistrySupplier<E> register(String name, Supplier<E> supplier) {
      return SkillRegistry.SKILLS.register(ResourceLocation.fromNamespaceAndPath("tensura", name), supplier);
   }

   public static void init() {
   }
}
