package io.github.manasmods.tensura.registry.race;

import dev.architectury.registry.registries.RegistrySupplier;
import io.github.manasmods.manascore.race.api.ManasRace;
import io.github.manasmods.manascore.race.impl.RaceRegistry;
import io.github.manasmods.tensura.race.beastfolk.BeastLordRace;
import io.github.manasmods.tensura.race.beastfolk.BeastfolkRace;
import io.github.manasmods.tensura.race.beastfolk.DivineBeastRace;
import io.github.manasmods.tensura.race.beastfolk.SpiritBeastRace;
import io.github.manasmods.tensura.race.demon.ArchDaemonRace;
import io.github.manasmods.tensura.race.demon.DaemonLordRace;
import io.github.manasmods.tensura.race.demon.DevilLordRace;
import io.github.manasmods.tensura.race.demon.GreaterDaemonRace;
import io.github.manasmods.tensura.race.demon.LesserDaemonRace;
import io.github.manasmods.tensura.race.dwarf.DivineDwarfRace;
import io.github.manasmods.tensura.race.dwarf.DwarfRace;
import io.github.manasmods.tensura.race.dwarf.DwarfSaintRace;
import io.github.manasmods.tensura.race.dwarf.EnlightenedDwarfRace;
import io.github.manasmods.tensura.race.elf.DivineElfRace;
import io.github.manasmods.tensura.race.elf.ElfRace;
import io.github.manasmods.tensura.race.elf.ElfSaintRace;
import io.github.manasmods.tensura.race.elf.EnlightenedElfRace;
import io.github.manasmods.tensura.race.giant.AncientGiantRace;
import io.github.manasmods.tensura.race.giant.DivineGiantRace;
import io.github.manasmods.tensura.race.giant.GiantRace;
import io.github.manasmods.tensura.race.goblin.EnlightenedHobgoblinRace;
import io.github.manasmods.tensura.race.goblin.GoblinRace;
import io.github.manasmods.tensura.race.goblin.HobgoblinRace;
import io.github.manasmods.tensura.race.goblin.HobgoblinSaintRace;
import io.github.manasmods.tensura.race.harpy.DivineBirdRace;
import io.github.manasmods.tensura.race.harpy.HarpyQueenRace;
import io.github.manasmods.tensura.race.harpy.HarpyRace;
import io.github.manasmods.tensura.race.harpy.SpiritBirdRace;
import io.github.manasmods.tensura.race.human.DivineHumanRace;
import io.github.manasmods.tensura.race.human.EnlightenedHumanRace;
import io.github.manasmods.tensura.race.human.HumanRace;
import io.github.manasmods.tensura.race.human.HumanSaintRace;
import io.github.manasmods.tensura.race.lizardman.DivineDragonRace;
import io.github.manasmods.tensura.race.lizardman.DragonewtRace;
import io.github.manasmods.tensura.race.lizardman.LizardmanRace;
import io.github.manasmods.tensura.race.lizardman.TrueDragonewtRace;
import io.github.manasmods.tensura.race.merfolk.DivineFishRace;
import io.github.manasmods.tensura.race.merfolk.EnlightenedMerfolkRace;
import io.github.manasmods.tensura.race.merfolk.MerfolkRace;
import io.github.manasmods.tensura.race.merfolk.MerfolkSaintRace;
import io.github.manasmods.tensura.race.ogre.DeathOniRace;
import io.github.manasmods.tensura.race.ogre.DivineFighterRace;
import io.github.manasmods.tensura.race.ogre.DivineOniRace;
import io.github.manasmods.tensura.race.ogre.EnlightenedOgreRace;
import io.github.manasmods.tensura.race.ogre.KijinRace;
import io.github.manasmods.tensura.race.ogre.MysticOniRace;
import io.github.manasmods.tensura.race.ogre.OgreRace;
import io.github.manasmods.tensura.race.ogre.SpiritOniRace;
import io.github.manasmods.tensura.race.ogre.WickedOniRace;
import io.github.manasmods.tensura.race.orc.DivineBoarRace;
import io.github.manasmods.tensura.race.orc.HighOrcRace;
import io.github.manasmods.tensura.race.orc.OrcDisasterRace;
import io.github.manasmods.tensura.race.orc.OrcLordRace;
import io.github.manasmods.tensura.race.orc.OrcRace;
import io.github.manasmods.tensura.race.orc.SpiritBoarRace;
import io.github.manasmods.tensura.race.slime.DemonSlimeRace;
import io.github.manasmods.tensura.race.slime.GodSlimeRace;
import io.github.manasmods.tensura.race.slime.MetalSlimeRace;
import io.github.manasmods.tensura.race.slime.SlimeRace;
import io.github.manasmods.tensura.race.vampire.DivineVampireRace;
import io.github.manasmods.tensura.race.vampire.GhoulRace;
import io.github.manasmods.tensura.race.vampire.VampireLordRace;
import io.github.manasmods.tensura.race.vampire.VampireOvercomerRace;
import io.github.manasmods.tensura.race.vampire.VampireRace;
import io.github.manasmods.tensura.race.wight.DivineSkeletonRace;
import io.github.manasmods.tensura.race.wight.SpiritSkeletonRace;
import io.github.manasmods.tensura.race.wight.WightKingRace;
import io.github.manasmods.tensura.race.wight.WightRace;
import java.util.function.Supplier;
import net.minecraft.resources.ResourceLocation;

public class TensuraRaces {
   public static final RegistrySupplier<ManasRace> BEASTFOLK = register("beastfolk", BeastfolkRace::new);
   public static final RegistrySupplier<ManasRace> BEAST_LORD = register("beast_lord", BeastLordRace::new);
   public static final RegistrySupplier<ManasRace> SPIRIT_BEAST = register("spirit_beast", SpiritBeastRace::new);
   public static final RegistrySupplier<ManasRace> DIVINE_BEAST = register("divine_beast", DivineBeastRace::new);
   public static final RegistrySupplier<ManasRace> HARPY = register("harpy", HarpyRace::new);
   public static final RegistrySupplier<ManasRace> HARPY_QUEEN = register("harpy_queen", HarpyQueenRace::new);
   public static final RegistrySupplier<ManasRace> SPIRIT_BIRD = register("spirit_bird", SpiritBirdRace::new);
   public static final RegistrySupplier<ManasRace> DIVINE_BIRD = register("divine_bird", DivineBirdRace::new);
   public static final RegistrySupplier<ManasRace> OGRE = register("ogre", OgreRace::new);
   public static final RegistrySupplier<ManasRace> KIJIN = register("kijin", KijinRace::new);
   public static final RegistrySupplier<ManasRace> ENLIGHTENED_OGRE = register("enlightened_ogre", EnlightenedOgreRace::new);
   public static final RegistrySupplier<ManasRace> MYSTIC_ONI = register("mystic_oni", MysticOniRace::new);
   public static final RegistrySupplier<ManasRace> WICKED_ONI = register("wicked_oni", WickedOniRace::new);
   public static final RegistrySupplier<ManasRace> SPIRIT_ONI = register("spirit_oni", SpiritOniRace::new);
   public static final RegistrySupplier<ManasRace> DEATH_ONI = register("death_oni", DeathOniRace::new);
   public static final RegistrySupplier<ManasRace> DIVINE_ONI = register("divine_oni", DivineOniRace::new);
   public static final RegistrySupplier<ManasRace> DIVINE_FIGHTER = register("divine_fighter", DivineFighterRace::new);
   public static final RegistrySupplier<ManasRace> GOBLIN = register("goblin", GoblinRace::new);
   public static final RegistrySupplier<ManasRace> HOBGOBLIN = register("hobgoblin", HobgoblinRace::new);
   public static final RegistrySupplier<ManasRace> ENLIGHTENED_HOBGOBLIN = register("enlightened_hobgoblin", EnlightenedHobgoblinRace::new);
   public static final RegistrySupplier<ManasRace> HOBGOBLIN_SAINT = register("hobgoblin_saint", HobgoblinSaintRace::new);
   public static final RegistrySupplier<ManasRace> GIANT = register("giant", GiantRace::new);
   public static final RegistrySupplier<ManasRace> ANCIENT_GIANT = register("ancient_giant", AncientGiantRace::new);
   public static final RegistrySupplier<ManasRace> DIVINE_GIANT = register("divine_giant", DivineGiantRace::new);
   public static final RegistrySupplier<ManasRace> ORC = register("orc", OrcRace::new);
   public static final RegistrySupplier<ManasRace> HIGH_ORC = register("high_orc", HighOrcRace::new);
   public static final RegistrySupplier<ManasRace> SPIRIT_BOAR = register("spirit_boar", SpiritBoarRace::new);
   public static final RegistrySupplier<ManasRace> ORC_LORD = register("orc_lord", OrcLordRace::new);
   public static final RegistrySupplier<ManasRace> ORC_DISASTER = register("orc_disaster", OrcDisasterRace::new);
   public static final RegistrySupplier<ManasRace> DIVINE_BOAR = register("divine_boar", DivineBoarRace::new);
   public static final RegistrySupplier<ManasRace> LIZARDMAN = register("lizardman", LizardmanRace::new);
   public static final RegistrySupplier<ManasRace> DRAGONEWT = register("dragonewt", DragonewtRace::new);
   public static final RegistrySupplier<ManasRace> TRUE_DRAGONEWT = register("true_dragonewt", TrueDragonewtRace::new);
   public static final RegistrySupplier<ManasRace> DIVINE_DRAGON = register("divine_dragon", DivineDragonRace::new);
   public static final RegistrySupplier<ManasRace> MERFOLK = register("merfolk", MerfolkRace::new);
   public static final RegistrySupplier<ManasRace> ENLIGHTENED_MERFOLK = register("enlightened_merfolk", EnlightenedMerfolkRace::new);
   public static final RegistrySupplier<ManasRace> MERFOLK_SAINT = register("merfolk_saint", MerfolkSaintRace::new);
   public static final RegistrySupplier<ManasRace> DIVINE_FISH = register("divine_fish", DivineFishRace::new);
   public static final RegistrySupplier<ManasRace> ELF = register("elf", ElfRace::new);
   public static final RegistrySupplier<ManasRace> ENLIGHTENED_ELF = register("enlightened_elf", EnlightenedElfRace::new);
   public static final RegistrySupplier<ManasRace> ELF_SAINT = register("elf_saint", ElfSaintRace::new);
   public static final RegistrySupplier<ManasRace> DIVINE_ELF = register("divine_elf", DivineElfRace::new);
   public static final RegistrySupplier<ManasRace> HUMAN = register("human", HumanRace::new);
   public static final RegistrySupplier<ManasRace> ENLIGHTENED_HUMAN = register("enlightened_human", EnlightenedHumanRace::new);
   public static final RegistrySupplier<ManasRace> HUMAN_SAINT = register("human_saint", HumanSaintRace::new);
   public static final RegistrySupplier<ManasRace> DIVINE_HUMAN = register("divine_human", DivineHumanRace::new);
   public static final RegistrySupplier<ManasRace> DWARF = register("dwarf", DwarfRace::new);
   public static final RegistrySupplier<ManasRace> ENLIGHTENED_DWARF = register("enlightened_dwarf", EnlightenedDwarfRace::new);
   public static final RegistrySupplier<ManasRace> DWARF_SAINT = register("dwarf_saint", DwarfSaintRace::new);
   public static final RegistrySupplier<ManasRace> DIVINE_DWARF = register("divine_dwarf", DivineDwarfRace::new);
   public static final RegistrySupplier<ManasRace> SLIME = register("slime", SlimeRace::new);
   public static final RegistrySupplier<ManasRace> METAL_SLIME = register("metal_slime", MetalSlimeRace::new);
   public static final RegistrySupplier<ManasRace> DEMON_SLIME = register("demon_slime", DemonSlimeRace::new);
   public static final RegistrySupplier<ManasRace> GOD_SLIME = register("god_slime", GodSlimeRace::new);
   public static final RegistrySupplier<ManasRace> GHOUL = register("ghoul", GhoulRace::new);
   public static final RegistrySupplier<ManasRace> VAMPIRE = register("vampire", VampireRace::new);
   public static final RegistrySupplier<ManasRace> VAMPIRE_OVERCOMER = register("vampire_overcomer", VampireOvercomerRace::new);
   public static final RegistrySupplier<ManasRace> VAMPIRE_LORD = register("vampire_lord", VampireLordRace::new);
   public static final RegistrySupplier<ManasRace> DIVINE_VAMPIRE = register("divine_vampire", DivineVampireRace::new);
   public static final RegistrySupplier<WightRace> WIGHT = register("wight", WightRace::new);
   public static final RegistrySupplier<ManasRace> WIGHT_KING = register("wight_king", WightKingRace::new);
   public static final RegistrySupplier<ManasRace> SPIRIT_SKELETON = register("spirit_skeleton", SpiritSkeletonRace::new);
   public static final RegistrySupplier<ManasRace> DIVINE_SKELETON = register("divine_skeleton", DivineSkeletonRace::new);
   public static final RegistrySupplier<ManasRace> LESSER_DAEMON = register("lesser_daemon", LesserDaemonRace::new);
   public static final RegistrySupplier<ManasRace> GREATER_DAEMON = register("greater_daemon", GreaterDaemonRace::new);
   public static final RegistrySupplier<ManasRace> ARCH_DAEMON = register("arch_daemon", ArchDaemonRace::new);
   public static final RegistrySupplier<ManasRace> DAEMON_LORD = register("daemon_lord", DaemonLordRace::new);
   public static final RegistrySupplier<ManasRace> DEVIL_LORD = register("devil_lord", DevilLordRace::new);

   private static <E extends ManasRace> RegistrySupplier<E> register(String name, Supplier<E> supplier) {
      return RaceRegistry.RACES.register(ResourceLocation.fromNamespaceAndPath("tensura", name), supplier);
   }

   public static void init() {
   }
}
